### ISSUE TITLE
Bower integration

### ISSUE THREAD

**Issue by dlewand691** [MartijnCuppens/rfs#1]
Thank you for sharing this! It's a fantastic technique that seems to solve a lot of problems. 

One suggestion/request is to add to Bower.io for maintainability and integration into projects.

**Comment by MartijnCuppens** [comment]
Thanks @dlewand691! You can install rfs with
```
bower install rfs
```

I've never used bower myself, so let me know if I've overlooked something.

But I may indeed add more documentation in the readme file about the installation with bower/npm/yarn.

**Comment by MartijnCuppens** [comment]
@dlewand691, I've added some documentation. Can you check if everything works fine now?

**Comment by dlewand691** [comment]
Looks good! Thank you!
