### ISSUE TITLE
Lack of spacing in calc() bugs code

### ISSUE THREAD

**Issue by dpw1** [MartijnCuppens/rfs#2]
My code was not working and then I realized it was a a problem at line 103: 

```
      @media (max-width: #{$mq-max-width}) {
        font-size: calc(#{$min-width} + #{$variable-width})#{$rfs-suffix};
      }
```

If you add a space before the $rfs-suffix it will work just fine!

```
      @media (max-width: #{$mq-max-width}) {
        font-size: calc(#{$min-width} + #{$variable-width}) #{$rfs-suffix};
      }
```

**Comment by MartijnCuppens** [comment]
Looks like a compiler-specific issue, there was no problem with the codepen demo:
https://codepen.io/MartijnCuppens/pen/ZBjdMy

Some people also reported the same issue, so thanks for the fix @dpw1!

https://github.com/MartijnCuppens/rfs/commit/9d13d656b3206d57697626b0e1c5544dd59534d5
