### ISSUE TITLE
Behavior in Safari 

### ISSUE THREAD

**Issue by EdGonzalez-** [MartijnCuppens/rfs#6]
This doesn't seem to behave the same on Safari (tested on 11.0.2). On the CodePen example, changing the window size in Chrome results in the font resizing from 16px down to around 14.5px, but on Safari it does not decrease below around 15.7 px.

**Comment by MartijnCuppens** [comment]
Thanks for the report @EdGonzalez-, it looks like Safari doesn't recalculate the value of vw in a calc()-function for the font-size property in iframes if the min-width, max-width or width is not set in vw and the iframe is resized, adding this line will solve this:
```css
_::-webkit-full-page-media, _:future, :root * {min-width: 0vw;}
```

Readmes and codepens are updated.
